### ISSUE TITLE
Nome no README

### ISSUE THREAD

**Issue by RafaLG18** [RafaLG18/GCMS-Rafael-Leal#2]
Professor @ramidedantas , por favor, adicionar nome no [README](https://github.com/RafaLG18/GCMS-Rafael-Leal/blob/main/README.md)

**Comment by ramidedantas** [comment]
@RafaLG18 ajuste o seu README para descrever o seu repositório. Agora está uma cópia do da turma.

**Comment by RafaLG18** [comment]
Readme ajustado.
